name: Generate docs from pod

on:
  push:
    branches:
      - main
    paths:
      - "README.pod"
      - ".github/workflows/doc.yml"

jobs:
  Run-deno-task-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@041b854f97b325bd60e53e9dc2de9cb9f9ac0cba # v1.1.4
        with:
          deno-version: vx.x.x
      - name: Check out repository code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Generate readme
        run: deno task docs
      - name: Create commits
        run: |
          git config user.name 'GitHub'
          git config user.email 'noreply@github.com'
          git add README.md doc/tataku-processor-intl_segmenter.txt --force
          git commit -m "docs: Generate docs"
          git clean -fdx
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
        with:
          title: "docs: Update docs"
          body: |
            This PR is created by [create-pull-request](https://github.com/peter-evans/create-pull-request).
            The docs are generated automaticaly.
          author: "GitHub <noreply@github.com>"
          delete-branch: true
